## NumPy tutorial
Click the image below to read the post online.

<a target="_blank" href="https://www.machinelearningnuggets.com/numpy-tutorial
"><img src="https://digitalpress.fra1.cdn.digitaloceanspaces.com/mhujhsj/2022/07/logo.png" alt="Open in ML Nuggets"></a>

In [ ]:
import numpy as np

# Numpy Arrays


## NumPy ndarry object

### Creating ndarry Object in NumPy

In [ ]:


# Create a NumPy array from a list and tuple

p_list = np.array([900, 200, 300, 99, 54, 80])
print("This is a list into numpy array:\n", p_list)
print("Type: ", type(p_list))

p_tuple = np.array((50, 60, 90, 105, 90.6, 30.8))
print("This is a tuple into numpy array:\n", p_tuple)
print("Type: ", type(p_tuple))

This is a list into numpy array:
 [900 200 300  99  54  80]
Type:  <class 'numpy.ndarray'>
This is a tuple into numpy array:
 [ 50.   60.   90.  105.   90.6  30.8]
Type:  <class 'numpy.ndarray'>


## Dimensions in Numpy array



In [ ]:

# Zero Dimensional Array

zerod_arr = np.array(30)
print(zerod_arr)
print("0-Dimensional: \n",  'Dim: ', zerod_arr.ndim)

# One Dimensional Array

oned_arr = np.array([30, 40, 60, 80, 10])
print(oned_arr)
print("1-Dimesional: \n", 'Dim: ', oned_arr.ndim)

# Two Dimensional Array

twod_arr = np.array([[20, 50, 60, 12], [10, 15, 24, 23]])
print(twod_arr)
print("2-Dimensional: \n", 'Dim: ', twod_arr.ndim)

# Three Dimensional Array

# We can pass in the 2-D array above

threed_arr = np.array([twod_arr])
print(threed_arr)

# or create one
threed_arr2 = np.array([
           [[1,2,3],[4,5,6],[7,8,9]],
           [[9,8,7],[6,5,4],[3,2,1]],
           [[1,2,3],[6,5,6],[7,8,9]]
           ])
print(threed_arr2)

print("3-Dimensional: \n", 'Dim: ', threed_arr.ndim, "&", threed_arr2.ndim)


30
0-Dimensional: 
 Dim:  0
[30 40 60 80 10]
1-Dimesional: 
 Dim:  1
[[20 50 60 12]
 [10 15 24 23]]
2-Dimensional: 
 Dim:  2
[[[20 50 60 12]
  [10 15 24 23]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [6 5 6]
  [7 8 9]]]
3-Dimensional: 
 Dim:  3 & 3


### Specifying the number of Dimensions Using **ndim** parameter

In [ ]:
#create an array of 6 dimensions

sixd_arr = np.array([1, 2, 3, 4], ndmin=6)

print(sixd_arr)
print("Dimensions :", sixd_arr.ndim)

[[[[[[1 2 3 4]]]]]]
Dimensions : 6


# NumPy Array Creation Functions


### np.linspace

In [ ]:
linspace_arr = np.linspace(2., 5., 6) # start, stop, interval
print(linspace_arr)

[2.  2.6 3.2 3.8 4.4 5. ]


### np.arange

In [ ]:
arange_arr = np.arange(1, 30., 4)
print(arange_arr)

[ 1.  5.  9. 13. 17. 21. 25. 29.]


### np.zeros

In [ ]:
zeros_arr = np.zeros((2, 3, 3))
print(zeros_arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### np.ones

In [ ]:
ones_arr = np.ones((2, 3, 3))
print(ones_arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### np.empty

In [ ]:
empty_arr = np.empty([5, 5], dtype=int)
print(empty_arr)

[[           22628176            11118976                 167
                   -1 8079584628061773859]
 [8027792918815405153 8007522626180508789 7381153981561839726
  7810123701326214176 8295668323982734177]
 [7236828442999421300 2338340670574978336 8367821614119415667
   748839365498708079 7595160661225840675]
 [7810775990839306094 7449355556930023017 8675467843668439909
  7956011654333542004 8245937412923350887]
 [8392750419555662368 7451606223107613545 7142773280752364910
  7017276114329693797    2926274656626035]]


# NumPy Data Types

## Creating simple dtypes

### Using data type names

In [ ]:
# 32-bit integer
int_dt = np.dtype(np.int32)
print(int_dt, "\n Type: ", int_dt.type)

#complex type
complex_dt = np.dtype(np.complex128)
print(complex_dt, "\n Type: ", complex_dt.type)

#Boolean
bool_dt = np.dtype(np.bool_)
print(bool_dt, "\n Type: ", bool_dt.type)

# float
float_dt = np.dtype(np.float32)
print(float_dt, "\n Type: ", float_dt.type)

#insigned integer

unsignedInt_dt = np.dtype(np.uint64)
print(unsignedInt_dt, "\n Type: ", unsignedInt_dt.type)

int32 
 Type:  <class 'numpy.int32'>
complex128 
 Type:  <class 'numpy.complex128'>
bool 
 Type:  <class 'numpy.bool_'>
float32 
 Type:  <class 'numpy.float32'>
uint64 
 Type:  <class 'numpy.uint64'>


### Using character codes

In [ ]:
# 32-bit signed integer
int_dt = np.dtype('i4')
print(int_dt, "\n Type: ", int_dt.type)

# 64-bit floating-point number
float_dt = np.dtype('f8')
print(float_dt, "\n Type: ", float_dt.type)

# complex
complex_dt = np.dtype('c16')
print(complex_dt, "\n Type: ", complex_dt.type)

# 64-bit unsigned integer
unsignedInt_dt = np.dtype('u8')
print(unsignedInt_dt, "\n Type: ", unsignedInt_dt.type)

int32 
 Type:  <class 'numpy.int32'>
float64 
 Type:  <class 'numpy.float64'>
complex128 
 Type:  <class 'numpy.complex128'>
uint64 
 Type:  <class 'numpy.uint64'>


### Check the data type using `dtype`

In [ ]:
threed_arr2 = np.array([
           [[1,2,3],[4,5,6],[7,8,9]],
           [[9,8,7],[6,5,4],[3,2,1]],
           [[1,2,3],[6,5,6],[7,8,9]]
           ])
print(threed_arr2.dtype)

arr_string = np.array(['apple', 'banana', 'cherry'])

print(arr_string.dtype)

int64
<U6


# Creating structured data types

## Creating a list of tuples where each field has one tuple

In [ ]:
#structured data types with a list of tuples

struct_dt_1 = np.dtype(([('name', 'S20'), ('age', np.int16), ('marks', 'f4', (2, 2))]))
print(struct_dt_1)

[('name', 'S20'), ('age', '<i2'), ('marks', '<f4', (2, 2))]


### Creating a list of comma-separated dtype specifications

In [ ]:
# comma separated dtypes

struct_dt_2 = np.dtype('S20, int16, f4')
print(struct_dt_2)

struct_dt_2s = np.dtype('3int16, float32, (2, 3)float64')
print(struct_dt_2s)

[('f0', 'S20'), ('f1', '<i2'), ('f2', '<f4')]
[('f0', '<i2', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))]


### Creating a dictionary of field parameter arrays

In [ ]:
struct_dt_3 = np.dtype({'names': ['name', 'salary'],
          'formats': ['i4', 'f4'],
          'offsets': [0, 4],
          'itemsize': 12})

print(struct_dt_3)

{'names':['name','salary'], 'formats':['<i4','<f4'], 'offsets':[0,4], 'itemsize':12}


# Structured arrays

In [ ]:
# Arrays with data type is a structures data type

structured_arr = np.array([('John', 23, 100.4), ('Mercy', 30, 58.3)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

print(structured_arr)
print(structured_arr.dtype) # checking the dtype of the array

[('John', 23, 100.4) ('Mercy', 30,  58.3)]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]


### Example

In [ ]:
model = ['Bentley', 'Toyota', 'Audi', 'Ford']
weight = [1400.8, 2500, 1600, 1700]
color = ['Blue', 'Green', 'White', 'Black']
speed = [240, 180, 300, 260]

vehicle_data = np.zeros(4, dtype={'names': ['model', 'weight', 'color', 'speed'],
                 'formats': ['U10', 'f8', 'U10', 'f8']
                 })

vehicle_data['model'] = model
vehicle_data['weight'] = weight
vehicle_data['color'] = color
vehicle_data['speed'] = speed

print("Data: \n", vehicle_data)

print("All vehicle Models:\n", vehicle_data['model'])
print("All vehicle Colors:\n", vehicle_data['color'])

Data: 
 [('Bentley', 1400.8, 'Blue', 240.) ('Toyota', 2500. , 'Green', 180.)
 ('Audi', 1600. , 'White', 300.) ('Ford', 1700. , 'Black', 260.)]
All vehicle Models:
 ['Bentley' 'Toyota' 'Audi' 'Ford']
All vehicle Colors:
 ['Blue' 'Green' 'White' 'Black']


# Indexing NumPy arrays

### Indexing a single element

In [ ]:
# Create a array of 15 elements 1-D

oned_arr = np.arange(15)
print('1-D Array: \n', oned_arr) # print the array
print('Item at index 4: \n', oned_arr[4])

# Reshape the 1-D to 2D

# Create a 2-D array
twod_arr = oned_arr.reshape(5, 3)
print('2-D Array: \n', twod_arr)
print('Item 10: \n', twod_arr[3, 1]) # Access Number 10 in the array(At row 3 column 1)

# Reshape the 2-D to 3-D

# Create the 3-D array
threed_arr = twod_arr.reshape(1, 5, 3)
print('3-D Array: \n', threed_arr)
print('Item 10: \n', threed_arr[0, 3, 1]) # Access Number 10 in 3-D array(At: 1-D array row 0, 2-D row 3, 3-D column 1


# NEGATIVE INDEXING

# GET THE LAST ELEMENT FROM THE 3-D ARRAY

last_element = threed_arr[0, -1, -1]
print('Last Element of 3-D array: \n', last_element)

1-D Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Item at index 4: 
 4
2-D Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Item 10: 
 10
3-D Array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]]
Item 10: 
 10
Last Element of 3-D array: 
 14


### Slicing

In [ ]:
# Create an array of 15 elements 1-D

oned_arr = np.arange(15)
print('1-D Array: \n', oned_arr) # print the array
print('From index 1-10: \n', oned_arr[1:10:2]) # SLICE FROM INDEX 1 TO 10 STEPS OF 2

print('Without stop and step: \n', oned_arr[1:])   # WITHOUT STOP AND STEP. SLICES FROM 
                                                   #INDEX 1 TO END
print('Without start and step: \n', oned_arr[:10]) # WITHOUT START AND STEP. SLICES FROM 
                                                   #INDEX 0 TO INDEX 10
print('Without start and stop: \n', oned_arr[::2]) # WITHOUT START AND STOP. SLICES FROM 
                                                   #INDEX 0 TO END STEPS OF 2

print('\n2-D ====================================================\n')
# Reshape the 1-D to 2D

# Create a 2-D array
twod_arr = oned_arr.reshape(5, 3)

print('2-D Array: \n', twod_arr)
print('From third element(slice index 0-2) : \n', twod_arr[2, 0:2:1]) # FROM THIRD ELEMENT[] 
                                                                      #SLICE INDEX 0 TO 2(INDEX 2 NOT INCLUDED)
                                                                      
print('Without stop and step: \n', twod_arr[2, 0:])  # FROM THIRD ELEMENT[] SLICE INDEX 0 TO END

print('Without start and step: \n', twod_arr[2, :1]) # FROM THIRD ELEMENT[] SLICES FROM 
                                                     #INDEX 0 TO INDEX 1(INDEX 1 NOT INCLUDED)
                                                     
print('Without start and stop: \n', twod_arr[2, ::2]) # FROM THIRD ELEMENT[] SLICES FROM 
                                                      #INDEX 0 TO END STEPS OF 2

1-D Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
From index 1-10: 
 [1 3 5 7 9]
Without stop and step: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Without start and step: 
 [0 1 2 3 4 5 6 7 8 9]
Without start and stop: 
 [ 0  2  4  6  8 10 12 14]

2-D ====================================================

2-D Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
From third element(slice index 0-2) : 
 [6 7]
Without stop and step: 
 [6 7 8]
Without start and step: 
 [6]
Without start and stop: 
 [6 8]


# NumPy array shapes and reshaping

### Finding Array Shapes with `shape`

In [ ]:
oned_arr = np.array([30, 40, 60, 80, 10])
print("1-D Array: \n", oned_arr)
print('Shape: ', oned_arr.shape)

twod_arr = np.array([[20, 50, 60, 12], [10, 15, 24, 23]])
print("2-D Array: \n", twod_arr)
print('Shape: ', twod_arr.shape)

threed_arr = np.array([[[20, 24], [30, 15]], [[35, 60], [57, 38]]])
print('3-D array: \n', threed_arr)
print('Shape: ', threed_arr.shape)

1-D Array: 
 [30 40 60 80 10]
Shape:  (5,)
2-D Array: 
 [[20 50 60 12]
 [10 15 24 23]]
Shape:  (2, 4)
3-D array: 
 [[[20 24]
  [30 15]]

 [[35 60]
  [57 38]]]
Shape:  (2, 2, 2)


### Reshaping with `reshape()`

In [ ]:
# Create a 1-D array

oned_arr = np.arange(15)
print('1-D Array: \n', oned_arr) # print the array


# Reshape the 1-D to 2-D

twod_arr = oned_arr.reshape(5, 3)
print('2-D Array from 1-D: \n', twod_arr)


# Reshape the 2-D to 3-D

threed_arr = twod_arr.reshape(1, 5, 3)
print('3-D Array from 2-D: \n', threed_arr)

1-D Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
2-D Array from 1-D: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
3-D Array from 2-D: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]]


# Broadcasting Numpy arrays

### Example

In [ ]:
print('ARRAYS OF SIMILAR SHAPE AND SIZE')

array_a = np.array([10, 20, 15, 30])
array_b = np.array([5, 4, 3, 6])
print('Shapes of a and b: \n', array_a.shape, array_b.shape)
print('Sum of both:\n', array_a + array_b) # success

print('ARRAYS OF DISIMILAR SHAPE AND SIZE')

array_a = np.array([10, 20, 15, 30])
array_b = np.array([5, 4, 3])
print('Shapes of a and b: \n', array_a.shape, array_b.shape)
try:
  print('Sum of both:\n', array_a + array_b) # Returns and error
except ValueError:
  print('Can\'t broadcast arrays of different shapes!')

ARRAYS OF SIMILAR SHAPE AND SIZE
Shapes of a and b: 
 (4,) (4,)
Sum of both:
 [15 24 18 36]
ARRAYS OF DISIMILAR SHAPE AND SIZE
Shapes of a and b: 
 (4,) (3,)
Can't broadcast arrays of different shapes!


### Successful Broadcasting

In [ ]:
array_a = np.array([[1, 1, 1],[20, 20, 20], [30, 30, 30], [40, 40, 40]])
array_b = np.array([1.0,2.0,3.0])
print('Array a:\n', array_a, 'SHAPE: ', array_a.shape)
print('Array b:\n', array_b, 'SHAPE: ', array_b.shape)

print('Sum of both: \n', array_a + array_b) # WILL BE SUCCESSFUL

Array a:
 [[ 1  1  1]
 [20 20 20]
 [30 30 30]
 [40 40 40]] SHAPE:  (4, 3)
Array b:
 [1. 2. 3.] SHAPE:  (3,)
Sum of both: 
 [[ 2.  3.  4.]
 [21. 22. 23.]
 [31. 32. 33.]
 [41. 42. 43.]]


### Failed Broadcasting

In [ ]:
array_a = np.array([[1, 1, 1],[20, 20, 20], [30, 30, 30], [40, 40, 40]])
array_b = np.array([1,2,3,4])
print('Array a:\n', array_a, 'SHAPE: ', array_a.shape)
print('Array b:\n', array_b, 'SHAPE: ', array_b.shape)
try:
  print('Sum of both: \n', array_a + array_b)
except ValueError:
   # handle value error
   print("Cannot broadcast arrays of different shape!")


Array a:
 [[ 1  1  1]
 [20 20 20]
 [30 30 30]
 [40 40 40]] SHAPE:  (4, 3)
Array b:
 [1 2 3 4] SHAPE:  (4,)
Cannot broadcast arrays of different shape!


# Iterating over NumPy arrays

### Getting values from 1-D, 2-D, 3-D arrays

In [ ]:
# Create a array of 15 elements 1-D

print('===1-D=== ARRAY \n')

oned_arr = np.arange(15)
print('1-D Array: \n', oned_arr) # print the array

print('LOOPING TO DISPLAY EACH ELEMENT')
for elem in oned_arr:
    print(elem)


# Reshape the 1-D to 2D

# Create a 2-D array
print('===2-D=== ARRAY \n')

twod_arr = oned_arr.reshape(5, 3)
print('2-D Array: \n', twod_arr)

print('LOOP TO GET EACH DIMENSION IN THE ARRAY')

for dimension in twod_arr:
    print(dimension)

print('LOOPING TO GET ACTUAL VALUES/SCALARS')
for dimension in twod_arr:
    for elem in dimension:
        print(elem)

# # Reshape the 2-D to 3-D

# Create the 3-D array
print('===3-D=== ARRAY \n')

threed_arr = twod_arr.reshape(1, 5, 3)
print('3-D Array: \n', threed_arr)

print('LOOPING TO GET ALL 2-D ARRAYS IN THE 3-D')
for array in threed_arr:
    print(array) # we have one 2-D array

print('LOOPING TO GET ALL VALUES/SCALARS: WE ITERATE OVER THE DIMENSIONS')
for array in threed_arr:
    for dimension in array:
        for elem in dimension:
            print(elem)

===1-D=== ARRAY 

1-D Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
LOOPING TO DISPLAY EACH ELEMENT
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
===2-D=== ARRAY 

2-D Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
LOOP TO GET EACH DIMENSION IN THE ARRAY
[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
LOOPING TO GET ACTUAL VALUES/SCALARS
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
===3-D=== ARRAY 

3-D Array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]]
LOOPING TO GET ALL 2-D ARRAYS IN THE 3-D
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
LOOPING TO GET ALL VALUES/SCALARS: WE ITERATE OVER THE DIMENSIONS
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


### Iterating with `nditer()` object

In [ ]:
fourd_arr = np.arange(10).reshape(1, 1, 5, 2) # create a 4-D array
print(fourd_arr)

# iterate with nditer object

for elem in np.nditer(fourd_arr): # otherwise would be 4 nested for loops
    print(elem)

[[[[0 1]
   [2 3]
   [4 5]
   [6 7]
   [8 9]]]]
0
1
2
3
4
5
6
7
8
9


# Modifying array elements

### Multiplying each elelement with 3

In [ ]:
fourd_arr = np.arange(10).reshape(1, 1, 5, 2) # create a 4-D array
print('Original Array: \n', fourd_arr)

# iterate with nditer object multiply each element with 3

for elem in np.nditer(fourd_arr, op_flags=['readwrite']): 
    elem[...] = 3*elem  # Each element is mulitplied by 3
print('Modified Array: \n', fourd_arr)

Original Array: 
 [[[[0 1]
   [2 3]
   [4 5]
   [6 7]
   [8 9]]]]
Modified Array: 
 [[[[ 0  3]
   [ 6  9]
   [12 15]
   [18 21]
   [24 27]]]]


### Canging the `dtype` of each element

In [ ]:
fourd_arr = np.arange(10).reshape(1, 1, 5, 2) # create a 4-D array
print('Original Array: \n', fourd_arr)

# iterate with nditer object change dtype

for elem in np.nditer(fourd_arr, flags=['buffered', 'external_loop'], op_dtypes='S'):
    print('Results of each element: \n', elem) # Each value is a str.

Original Array: 
 [[[[0 1]
   [2 3]
   [4 5]
   [6 7]
   [8 9]]]]
Results of each element: 
 [b'0' b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9']


# Numpy string functions

### `np.char.add()`
### `np.char.multiply()`

In [ ]:
print('add()')

string_arr1 = np.char.add(['Goodbye ', 'Thank you for '], ['Derrick', 'Visiting'])
print(string_arr1)

for elem in string_arr1:
    print(elem, end='. ')

print('\n')

print('multiply()')
print(np.char.multiply('buffalo ', 8)) # Completely valid word

add()
['Goodbye Derrick' 'Thank you for Visiting']
Goodbye Derrick. Thank you for Visiting. 

multiply()
buffalo buffalo buffalo buffalo buffalo buffalo buffalo buffalo 


### `np.char.center()`

In [ ]:
print(np.char.center(['NumPy', 'Tutorial'], 20, fillchar = '>')) # (arr, width, fillchar)

['>>>>>>>NumPy>>>>>>>>' '>>>>>>Tutorial>>>>>>']


### `np.char.lower()`
### `np.char.upper()`
### `np.char.capitalize()`

In [ ]:
print('convert string to lower')
print(np.char.lower('NUMPY IS INTERESTING, IS IT?\n'))

print('CONVERT STRING TO UPPERCASE')
print(np.char.upper('numpy is interesting, is it?\n'))

print('Capitalize string')
print(np.char.capitalize('numpy is interesting, is it?'))

convert string to lower
numpy is interesting, is it?

CONVERT STRING TO UPPERCASE
NUMPY IS INTERESTING, IS IT?

Capitalize string
Numpy is interesting, is it?


### `np.char.join()`
### `np.char.split()`

In [ ]:
print('join()')
print(np.char.join([':', '-'], ['ymd', 'dmy']))

print('split()')
print(np.char.split('Eat, Sleep, Code, Connect', sep=','))

join()
['y:m:d' 'd-m-y']
split()
['Eat', ' Sleep', ' Code', ' Connect']


# NumPy mathematical operations

## Rounding

### `np.around()`
### `np.floor()`
### `np.ceil()`
### `np.trunc()`
### `np.fix()`

In [ ]:
print('ROUNDING\n')
print('Array: ', [20.1, 30.6, 4.55, 5.4, 8.63, 0.3, -2.7])

print(np.char.center(' np.around() ', 25, fillchar='='))
round_arr = np.around([20.1, 30.6, 4.55, 5.4, 8.63, 0.3, -2.7])
print(round_arr)

print(np.char.center(' np.floor() ', 25, fillchar='='))
floor_arr = np.floor([20.1, 30.6, 4.55, 5.4, 8.63, 0.3, -2.7])
print(floor_arr)

print(np.char.center(' np.ceil() ', 25, fillchar='='))
ceil_arr = np.ceil([20.1, 30.6, 4.55, 5.4, 8.63, 0.3, -2.7])
print(ceil_arr)

print(np.char.center(' np.trunc() ', 25, fillchar='='))
trunc_arr = np.trunc([20.1, 30.6, 4.55, 5.4, 8.63, 0.3, -2.7])
print(trunc_arr)

ROUNDING

Array:  [20.1, 30.6, 4.55, 5.4, 8.63, 0.3, -2.7]
====== np.around() ======
[20. 31.  5.  5.  9.  0. -3.]
======= np.floor() ======
[20. 30.  4.  5.  8.  0. -3.]
======= np.ceil() =======
[21. 31.  5.  6.  9.  1. -2.]
======= np.trunc() ======
[20. 30.  4.  5.  8.  0. -2.]


## Trigonometry

### `np.sin`
### `np.cos`
### `np.tan`
### `np.arcsin`
### `np.arccos`
### `np.arctan`

In [ ]:
print('Trigonometry\n')

angle_arr = np.array([0,45, 60, 80, 90, 180, 270])
print('Array: ', angle_arr)

print(np.char.center(' np.sin ', 25, fillchar='='))
sin_values = np.sin(angle_arr * np.pi/180)
print(sin_values)

print(np.char.center(' np.arcsin (sine Inverse) ', 35, fillchar='='))
arcsin_values = np.arcsin(sin_values)  # sine inverse ofg angles(in radians)
print(arcsin_values)

print(np.char.center(' np.cos ', 25, fillchar='='))
cos_values = np.cos(angle_arr * np.pi/180)
print(cos_values)

print(np.char.center(' np.arccos (cos inverse) ', 35, fillchar='='))
arccos_values = np.arccos(cos_values)  # cosine inverse of angles(in radians)
print(arccos_values)

print(np.char.center(' np.tan ', 25, fillchar='='))
tan_values = np.tan(angle_arr * np.pi/180)
print(tan_values)

print(np.char.center(' np.arctan (tangent inverse) ', 35, fillchar='='))
arctan_values = np.arctan(tan_values)  # tangent inverse of angles(in radians)
print(arctan_values)

Trigonometry

Array:  [  0  45  60  80  90 180 270]
========= np.sin ========
[ 0.00000000e+00  7.07106781e-01  8.66025404e-01  9.84807753e-01
  1.00000000e+00  1.22464680e-16 -1.00000000e+00]
===== np.arcsin (sine Inverse) ====
[ 0.00000000e+00  7.85398163e-01  1.04719755e+00  1.39626340e+00
  1.57079633e+00  1.22464680e-16 -1.57079633e+00]
========= np.cos ========
[ 1.00000000e+00  7.07106781e-01  5.00000000e-01  1.73648178e-01
  6.12323400e-17 -1.00000000e+00 -1.83697020e-16]
===== np.arccos (cos inverse) =====
[0.         0.78539816 1.04719755 1.3962634  1.57079633 3.14159265
 1.57079633]
========= np.tan ========
[ 0.00000000e+00  1.00000000e+00  1.73205081e+00  5.67128182e+00
  1.63312394e+16 -1.22464680e-16  5.44374645e+15]
=== np.arctan (tangent inverse) ===
[ 0.00000000e+00  7.85398163e-01  1.04719755e+00  1.39626340e+00
  1.57079633e+00 -1.22464680e-16  1.57079633e+00]


## Finding extremes in NumPy array

### `np.amax()`
### `np.amin()`
### `np.argmax()`

In [ ]:
array = np.array([[30, 10, 15, 80, 5], [3, 18, 60, 11, 25], [100, 40, 12, 8, 101]])
print(array)

print(np.char.center(' np.amax() MAX VALUE IN EACH COLUMN ', 45, fillchar='='))
print(np.amax(array, axis = 0)) # column-wise iteration:
                                # Returns max value of each column

print(np.char.center(' np.amin() MIN VALUE IN EACH ROW ', 45, fillchar='='))
print(np.amin(array, axis = 1)) # row-wise iteration:
                                  # Returns index of min value of each row

print(np.char.center(' np.argmax() MAX INDEX IN EACH COLUMN ', 45, fillchar='='))
print(np.argmax(array, axis = 0)) # column-wise iteration:
                                  # Returns index of max value of each column

print(np.char.center(' np.argmin() MIN INDEX IN EACH ROW ', 45, fillchar='='))
print(np.argmin(array, axis = 1)) # row-wise iteration:
                                  # Returns index of min value of each row

[[ 30  10  15  80   5]
 [  3  18  60  11  25]
 [100  40  12   8 101]]
===== np.amax() MAX VALUE IN EACH COLUMN ====
[100  40  60  80 101]
====== np.amin() MIN VALUE IN EACH ROW ======
[5 3 8]
==== np.argmax() MAX INDEX IN EACH COLUMN ===
[2 2 1 0 2]
===== np.argmin() MIN INDEX IN EACH ROW =====
[4 0 3]


# NumPy arithmetic operations

### `np.add()`
### `np.sum()`
### `np.subtract()`
### `np.divide()`
### `np.multiply()`
### `np.reciprocal()`
### `np.mod()`
### `np.power()`

In [ ]:
print('Arithmetic Operations')

array_a = np.array([10, 20, 15, 30,])
array_b = np.array([3, 4, 2, 7])
print('Array a: ', array_a, '\nArray b: ', array_b)

print(np.char.center(' np.add() Addition ', 35, fillchar='='))
addition = np.add(array_a, array_b)
print(addition)

print(np.char.center(' np.sum() Sum ', 35, fillchar='='))
sum_el = np.add(array_a, array_b) #row totals
print(sum_el)

print(np.char.center(' np.subtract() Subtraction ', 35, fillchar='='))
subtraction = np.subtract(array_a, array_b)
print(subtraction)

print(np.char.center(' np.divide() Division ', 35, fillchar='='))
division = np.divide(array_a, array_b)
print(division)

print(np.char.center(' np.mod() Modulus ', 35, fillchar='='))
modulus = np.mod(array_a, array_b)
print(modulus)

print(np.char.center(' np.power() Power ', 35, fillchar='='))
power = np.power(array_a, array_b)
print(power)

print(np.char.center(' np.reciprocal() Reciprocal ', 35, fillchar='='))
array_r = np.array([10, 0.22, 15, 30,])
print('Array r:', array_r)
reciprocal = np.reciprocal(array_r)
reciprocal2 = np.reciprocal(array_b)
print(reciprocal, '\n', reciprocal2)

Arithmetic Operations
Array a:  [10 20 15 30] 
Array b:  [3 4 2 7]
======== np.add() Addition ========
[13 24 17 37]
=========== np.sum() Sum ==========
[13 24 17 37]
==== np.subtract() Subtraction ====
[ 7 16 13 23]
======= np.divide() Division ======
[3.33333333 5.         7.5        4.28571429]
========= np.mod() Modulus ========
[1 0 1 2]
========= np.power() Power ========
[       1000      160000         225 21870000000]
==== np.reciprocal() Reciprocal ===
Array r: [10.    0.22 15.   30.  ]
[0.1        4.54545455 0.06666667 0.03333333] 
 [0 0 0 0]


# NumPy statistical operations

### Square root `np.sqrt()`

In [ ]:
array = np.array([25, 225, 256, 16, 100])
array2 = np.array([[400, 900, 1600], [2500, 3600, 4900]])

print('1-D array:\n', array)
print('1-D sqrt:\n', np.sqrt(array))
print('2-D array:\n', array2)
print('2-D sqrt:\n', np.sqrt(array2))

1-D array:
 [ 25 225 256  16 100]
1-D sqrt:
 [ 5. 15. 16.  4. 10.]
2-D array:
 [[ 400  900 1600]
 [2500 3600 4900]]
2-D sqrt:
 [[20. 30. 40.]
 [50. 60. 70.]]


### Mean `np.mean`

In [ ]:
array = np.array([30, 200, 100])
array2 = np.array([[4, 9, 2], [15, 20, 5]])

print('1-D array:\n', array)
print('1-D mean:\n', np.mean(array))
print('2-D array:\n', array2)
print('2-D mean:\n', np.mean(array2, axis=0)) # mean on each column


1-D array:
 [ 30 200 100]
1-D mean:
 110.0
2-D array:
 [[ 4  9  2]
 [15 20  5]]
2-D mean:
 [ 9.5 14.5  3.5]


### Median `np.median()`



In [ ]:
array = np.array([30, 200, 100])
array2 = np.array([[4, 9, 2], [15, 20, 5]])

print('1-D array:\n', array)
print('1-D median:\n', np.median(array))
print('2-D array:\n', array2)
print('2-D median:\n', np.median(array2, axis=1)) # mean on each row


1-D array:
 [ 30 200 100]
1-D median:
 100.0
2-D array:
 [[ 4  9  2]
 [15 20  5]]
2-D median:
 [ 4. 15.]


### Variance `np.var()`

In [ ]:
array = np.array([30, 200, 100])
array2 = np.array([[4, 9, 2], [15, 20, 5]])

print('1-D array:\n', array)
print('1-D variance:\n', np.var(array))
print('2-D array:\n', array2)
print('2-D variance:\n', np.var(array2, axis=1)) # mean on each row


1-D array:
 [ 30 200 100]
1-D variance:
 4866.666666666667
2-D array:
 [[ 4  9  2]
 [15 20  5]]
2-D variance:
 [ 8.66666667 38.88888889]


### Standard deviation `np.std`

In [ ]:
array = np.array([30, 200, 100])
array2 = np.array([[4, 9, 2], [15, 20, 5]])

print('1-D array:\n', array)
print('1-D standard deviation:\n', np.std(array))
print('2-D array:\n', array2)
print('2-D standard deviation:\n', np.std(array2, axis=1)) # mean on each 


1-D array:
 [ 30 200 100]
1-D standard deviation:
 69.7614984548545
2-D array:
 [[ 4  9  2]
 [15 20  5]]
2-D standard deviation:
 [2.94392029 6.23609564]


# Generating random numbers

In [ ]:
from numpy import random

### Generate random intgers and floats

In [ ]:
random_int = np.random.randint(25) # generate random number from 0 to 25;
print(random_int)

random_float = np.random.rand() # returns a random float from 0-1
print(random_float)


6
0.4284667240907487


### Generate random arrays

In [ ]:
print('Generate 1-D array with randint()')
random_arr = np.random.randint(30, size=10) # 10 random integers from 0 to 30
print(random_arr)

print('Generate 2-D array with randint() 6 rows each with 5 random numbers')
random_arr = np.random.randint(30, size=(6, 5)) # six rows with 5 random integers each from 0-25
print(random_arr)

print('Generate 1-D array with 10 random floats')
random_float_arr = np.random.rand(10)
print(random_float_arr)

print('Generate 2-D array with 6 rows 5 random floats Each row')
random_float_arr = np.random.rand(6, 5) # six rows each with 5 random numbers
print(random_float_arr)

Generate 1-D array with randint()
[12  8  5  4 28 11 19 18  2  3]
Generate 2-D array with randint() 6 rows each with 5 random numbers
[[26  9  7 28  3]
 [11 10  4  4  0]
 [28 22  0 11 23]
 [ 9 12 25  8 12]
 [18  8 16  5  8]
 [29  0 14 12 16]]
Generate 1-D array with 10 random floats
[0.84581516 0.58716253 0.53736494 0.26448574 0.64838237 0.78445528
 0.53717976 0.62920012 0.01386375 0.56638558]
Generate 2-D array with 6 rows 5 random floats Each row
[[0.8889583  0.38552197 0.67639992 0.39929053 0.24923701]
 [0.62837703 0.13946745 0.68712813 0.30305717 0.99393406]
 [0.7634123  0.55584042 0.88927623 0.59139915 0.41127375]
 [0.11550748 0.72722908 0.02255809 0.27702654 0.28517646]
 [0.08647712 0.64961874 0.91675152 0.57285547 0.2769331 ]
 [0.64757095 0.98569239 0.35794809 0.78425843 0.19589397]]


### Generate random numbers from an array

In [ ]:
rand_num_from_arr = np.random.choice([10, 20, 100, 2])
print(rand_num_from_arr)

# Generate Array
rand_arr_from_arr2 = np.random.choice([10, 20, 100, 2], size=(2, 2))
print(rand_arr_from_arr2)

20
[[ 10   2]
 [100   2]]


# Concatenating arrays `np.concatenate()`

In [ ]:
array_a = np.array([[10, 15, 30], [16, 24, 16]])
array_b = np.array([[11,21,33], [14, 10, 18]])

print('Concatenate with no axis')
print(np.concatenate((array_a, array_b)))

print('Concatenate with axis=0')
print(np.concatenate((array_a, array_b), axis=0))

print('Concatenate with axis=1')
print(np.concatenate((array_a, array_b), axis=1))

Concatenate with no axis
[[10 15 30]
 [16 24 16]
 [11 21 33]
 [14 10 18]]
Concatenate with axis=0
[[10 15 30]
 [16 24 16]
 [11 21 33]
 [14 10 18]]
Concatenate with axis=1
[[10 15 30 11 21 33]
 [16 24 16 14 10 18]]


# Sorting NumPy arrays `numpy.sort()`

In [ ]:
array_a = np.array([[10, 15, 30, 2], [16, 24, 16, 4]])

print('Sort Array with axis=-1 which is Default')
print(np.sort(array_a))

print('Sort with axis=None: Array is flattened')
print(np.sort(array_a, axis=None))

print('Sort with axis=0:')
print(np.sort(array_a, axis=0))

print('Sort with axis=1:')
print(np.sort(array_a, axis=1))

print('===Sort Structured Array===')

data_dtype = [('model', 'U10'), ('weight', 'f8'), ('color', 'U10'), ('speed', 'f8')]
vehicle_data_values = [('Bentley', 1400.8, 'Blue', 240), ('Toyota', 2500, 'Green', 
180), ('Audi', 1600, 'White', 300), ('Ford', 1700, 'Black', 260)]

vehicle_info = np.array(vehicle_data_values, dtype=data_dtype)
print('Unsorted Vehicle info:')
print(vehicle_info)
print('Sorted vehicle info by model and speed')
print(np.sort(vehicle_info, order=['model', 'speed']))

Sort Array with axis=-1 which is Default
[[ 2 10 15 30]
 [ 4 16 16 24]]
Sort with axis=None: Array is flattened
[ 2  4 10 15 16 16 24 30]
Sort with axis=0:
[[10 15 16  2]
 [16 24 30  4]]
Sort with axis=1:
[[ 2 10 15 30]
 [ 4 16 16 24]]
===Sort Structured Array===
Unsorted Vehicle info:
[('Bentley', 1400.8, 'Blue', 240.) ('Toyota', 2500. , 'Green', 180.)
 ('Audi', 1600. , 'White', 300.) ('Ford', 1700. , 'Black', 260.)]
Sorted vehicle info by model and speed
[('Audi', 1600. , 'White', 300.) ('Bentley', 1400.8, 'Blue', 240.)
 ('Ford', 1700. , 'Black', 260.) ('Toyota', 2500. , 'Green', 180.)]


# Filtering NumPy arrays

In [ ]:
arr_to_filter = np.array([30, 40, 50, 100, 130, 90])

# Create a empty list: will contain the boolean values
# As we iterate through the array we check if a value meets a
# condition and then insert a True or False based on satisfaction of
# the condition

boolean_list = []

for elem in arr_to_filter:
    if elem > 55:
        boolean_list.append(True)
    else:
        boolean_list.append(False)
# now we create a new list based on the boolean values of the boolean list

new_filtered_arr = arr_to_filter[boolean_list]

print('Origina arr: \n', arr_to_filter)
print('Boolean list for filter: \n', boolean_list)
print('New Array: \n', new_filtered_arr)

Origina arr: 
 [ 30  40  50 100 130  90]
Boolean list for filter: 
 [False, False, False, True, True, True]
New Array: 
 [100 130  90]


# Searching values in arrays `where`

In [ ]:
array_a = np.array([30, 40, 20, 15, 30, 15, 50])
value_s = np.where(array_a == 15)
print(value_s)
# we have 15 at index 3 and 5 hence array[3, 5]


# Below, if value is less than 30 return it else multiply by 2
value_s2 = np.where(array_a < 30, array_a, 2*array_a)
print(value_s2)

(array([3, 5]),)
[ 60  80  20  15  60  15 100]


## Where to go from here
Follow us on [LinkedIn](https://www.linkedin.com/company/mlnuggets), [Twitter](https://twitter.com/ml_nuggets), [GitHub](https://github.com/mlnuggets) and subscribe to our [blog](https://www.machinelearningnuggets.com/#/portal) so that you don't miss a new issue.